/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.idmProjet.ui.internal.IdmProjetActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IdmProjetActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
