/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDelete()
 * @model
 * @generated
 */
public interface Delete extends JsonOperation
{
} // Delete
