/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Json#getPairs <em>Pairs</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Json#getOperations <em>Operations</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getJson()
 * @model
 * @generated
 */
public interface Json extends Value
{
  /**
   * Returns the value of the '<em><b>Pairs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Pair}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pairs</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getJson_Pairs()
   * @model containment="true"
   * @generated
   */
  EList<Pair> getPairs();

  /**
   * Returns the value of the '<em><b>Operations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.JsonOperation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operations</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getJson_Operations()
   * @model containment="true"
   * @generated
   */
  EList<JsonOperation> getOperations();

} // Json
