/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Search</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Search#getKeyId <em>Key Id</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Search#getKey <em>Key</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSearch()
 * @model
 * @generated
 */
public interface Search extends JsonOperation
{
  /**
   * Returns the value of the '<em><b>Key Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key Id</em>' attribute.
   * @see #setKeyId(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSearch_KeyId()
   * @model
   * @generated
   */
  String getKeyId();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Search#getKeyId <em>Key Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key Id</em>' attribute.
   * @see #getKeyId()
   * @generated
   */
  void setKeyId(String value);

  /**
   * Returns the value of the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' attribute.
   * @see #setKey(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSearch_Key()
   * @model
   * @generated
   */
  String getKey();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Search#getKey <em>Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' attribute.
   * @see #getKey()
   * @generated
   */
  void setKey(String value);

} // Search
